//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizFizyczny.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizFizEntities : DbContext
    {
        public QuizFizEntities()
            : base("name=QuizFizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<Odpowiedzi> Odpowiedzi { get; set; }
        public virtual DbSet<PoprawneOdpowiedzi> PoprawneOdpowiedzi { get; set; }
        public virtual DbSet<Pytania> Pytania { get; set; }
        public virtual DbSet<Rozgrywka> Rozgrywka { get; set; }
        public virtual DbSet<RozgrywkaOdp> RozgrywkaOdp { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
