//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizFizyczny.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedzi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odpowiedzi()
        {
            this.PoprawneOdpowiedzi = new HashSet<PoprawneOdpowiedzi>();
            this.RozgrywkaOdp = new HashSet<RozgrywkaOdp>();
            this.RozgrywkaOdp1 = new HashSet<RozgrywkaOdp>();
            this.RozgrywkaOdp2 = new HashSet<RozgrywkaOdp>();
        }
    
        public int id { get; set; }
        public int id_pytanie { get; set; }
        public string odpowiedz { get; set; }
    
        public virtual Odpowiedzi Odpowiedzi1 { get; set; }
        public virtual Odpowiedzi Odpowiedzi2 { get; set; }
        public virtual Pytania Pytania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoprawneOdpowiedzi> PoprawneOdpowiedzi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozgrywkaOdp> RozgrywkaOdp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozgrywkaOdp> RozgrywkaOdp1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozgrywkaOdp> RozgrywkaOdp2 { get; set; }
    }
}
