//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizFizyczny.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozgrywka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rozgrywka()
        {
            this.RozgrywkaOdp = new HashSet<RozgrywkaOdp>();
        }
    
        public int id { get; set; }
        public int idPytanie1 { get; set; }
        public int idPytanie2 { get; set; }
        public int idPytanie3 { get; set; }
        public int idUztk1 { get; set; }
        public Nullable<int> idUztk2 { get; set; }
    
        public virtual Pytania Pytania { get; set; }
        public virtual Pytania Pytania1 { get; set; }
        public virtual Pytania Pytania2 { get; set; }
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        public virtual Uzytkownicy Uzytkownicy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RozgrywkaOdp> RozgrywkaOdp { get; set; }
    }
}
